version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-stretch-browsers
    steps:
      - checkout
      - run: echo "hello world"
  test:
    docker:
      - image: circleci/node:8-stretch-browsers
    steps:
      - checkout
      - run:
          name: Install jsonlint
          command: sudo npm install jsonlint -g
      - run:
          name: To grant execute permission
          command: chmod 777 ./checkJson.sh
      - run:
          name: Json Validation Test
          command: ./checkJson.sh
      - store_artifacts:
          path: test-results.xml
          prefix: tests

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
